name: APB CI

on: push

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - run: pwd

      - run: ls

      - run: git clone https://github.com/accellera-official/uvm-core.git

      - run: |
          python3 - <<EOF
          path = "uvm-core/src/dpi/uvm_hdl.c"

          with open(path, "r") as f:
              data = f.read()

          old = '#error "hdl vendor backend is missing"'

          new = '''#ifdef VERILATOR
#include "uvm_hdl_verilator.c"
#else
#error "hdl vendor backend is missing"
#endif'''

          data = data.replace(old, new)

          with open(path, "w") as f:
              f.write(data)
          EOF

      - run: |
          cat > uvm-core/src/dpi/uvm_hdl_verilator.c <<EOF
          #include <stdio.h>

          int uvm_hdl_check_path(char *path)
          {
              return 1;
          }

          int uvm_hdl_read(char *path, p_vpi_vecval value)
          {
              return 1;
          }

          int uvm_hdl_deposit(char *path, p_vpi_vecval value)
          {
              return 1;
          }

          int uvm_hdl_release(char *path)
          {
              return 1;
          }
          EOF

      - run: |
          unset VERILATOR_ROOT
          verilator --binary --sv \
          --vpi \
          --top-module tb \
          -CFLAGS "-DVERILATOR" \
          -I./uvm-core/src \
          ./uvm-core/src/uvm_pkg.sv \
          ./uvm-core/src/dpi/uvm_dpi.cc \
          ./uvm-core/src/dpi/uvm_regex.cc \
          -f flist.f

      - run: ./obj_dir/Vtb
